#pragma once

#include "IEbpfModule.hpp"
#include "print_test.skel.h" // Generated by bpftool

class SyscallModule : public IEbpfModule {
private:
    struct print_test *skel = nullptr;
    const char* name = "SyscallMonitor";

public:
    SyscallModule();
    ~SyscallModule();

    bool open() override;

    bool load(int shared_rb_fd) override;

    bool attach() override;

    void process_event(const common::ebpf_event* event, size_t size) override;

    common::bpf_module_id_t get_id() const override;

    const char* get_name() const override;
};
