#pragma once

#include "IEbpfModule.hpp"
#include "daemon_hardener.skel.h" // Generated by bpftool
#include "ebpf_types.h"
#include <memory>

namespace OdinSight::Daemon::Monitor::Kernel::Modules {

class DaemonModule final : public IEbpfModule {
  friend IEbpfModule;

  using SkelPtr = std::unique_ptr<struct daemon_hardener, decltype(&daemon_hardener__destroy)>;

private:
  SkelPtr m_skel{nullptr, daemon_hardener__destroy};

  DaemonModule() : IEbpfModule(EbpfModuleId::MODULE_LSM_SHIELD, "Syscall") {}

public:
  ~DaemonModule() = default;

  // Singleton enforcement
  DaemonModule(const DaemonModule&)            = delete;
  DaemonModule& operator=(const DaemonModule&) = delete;

  DaemonModule(DaemonModule&&)            = delete;
  DaemonModule& operator=(DaemonModule&&) = delete;

  Odin::Result<void> open() override;
  Odin::Result<void> load(int shared_rb_fd) override;
  Odin::Result<void> attach() override;
  void               processEvent(const ebpf_event* event, size_t size) override;
};

} // namespace OdinSight::Daemon::Monitor::Kernel::Modules
