#pragma once

#include "IEbpfModule.hpp"
#include "ebpf_types.h"
#include "game_protection.skel.h" // Generated by bpftool
#include <memory>
#include <stdint.h>

namespace OdinSight::Daemon::Monitor::Kernel::Modules {

class GameModule final : public IEbpfModule {
  friend IEbpfModule;

  using SkelPtr = std::unique_ptr<struct game_protection, decltype(&game_protection__destroy)>;

private:
  uint64_t m_cg_id;
  SkelPtr  m_skel{nullptr, game_protection__destroy};

  explicit GameModule(uint64_t cg_id)
      : IEbpfModule(EbpfModuleId::MODULE_GAME, "Game"), m_cg_id(cg_id) {}

public:
  ~GameModule() = default;

  // Singleton enforcement
  GameModule(const GameModule&)            = delete;
  GameModule& operator=(const GameModule&) = delete;

  GameModule(GameModule&&)            = delete;
  GameModule& operator=(GameModule&&) = delete;

  Odin::Result<void> open() override;
  Odin::Result<void> load(int shared_rb_fd) override;
  Odin::Result<void> attach() override;
  void               processEvent(const ebpf_event* event, size_t size) override;
};

} // namespace OdinSight::Daemon::Monitor::Kernel::Modules
