#pragma once

#include "IEbpfModule.hpp"
#include "ebpf_types.h"
#include "print_test.skel.h" // Generated by bpftool
#include <memory>

namespace OdinSight::Daemon::Monitor::Kernel::Modules {

class SyscallModule final : public IEbpfModule {
  friend IEbpfModule;

  using SkelPtr = std::unique_ptr<struct print_test, decltype(&print_test__destroy)>;

private:
  SkelPtr m_skel{nullptr, print_test__destroy};

  SyscallModule() : IEbpfModule(EbpfModuleId::MODULE_LSM_SHIELD, "Syscall") {}

public:
  ~SyscallModule() = default;

  // Singleton enforcement
  SyscallModule(const SyscallModule&)            = delete;
  SyscallModule& operator=(const SyscallModule&) = delete;

  SyscallModule(SyscallModule&&)            = delete;
  SyscallModule& operator=(SyscallModule&&) = delete;

  Odin::Result<void> open() override;
  Odin::Result<void> load(int shared_rb_fd) override;
  Odin::Result<void> attach() override;
  void               processEvent(const ebpf_event* event, size_t size) override;
};

} // namespace OdinSight::Daemon::Monitor::Kernel::Modules
