#pragma once

#include "IEbpfModule.hpp"
#include "ebpf_types.h"
#include "print_test.skel.h" // Generated by bpftool

namespace OdinSight::Daemon::Monitor::Kernel::Modules {

class SyscallModule : public IEbpfModule {
private:
  struct print_test *m_skel = nullptr;
  const char        *m_name = "SyscallMonitor";

public:
  SyscallModule();
  ~SyscallModule();

  bool open() override;
  bool load(int shared_rb_fd) override;
  bool attach() override;
  void processEvent(const ebpf_event *event, size_t size) override;

  EbpfModuleId getId() const override { return EbpfModuleId::MODULE_LSM_SHIELD; }

  const char *getName() const override { return "SyscallMonitor"; }
};

} // namespace OdinSight::Daemon::Monitor::Kernel::Modules
