/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __MASTER_SKEL_H__
#define __MASTER_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

#define BPF_SKEL_SUPPORTS_MAP_AUTO_ATTACH 1

struct master {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *rb;
	} maps;

#ifdef __cplusplus
	static inline struct master *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct master *open_and_load();
	static inline int load(struct master *skel);
	static inline int attach(struct master *skel);
	static inline void detach(struct master *skel);
	static inline void destroy(struct master *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
master__destroy(struct master *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
master__create_skeleton(struct master *obj);

static inline struct master *
master__open_opts(const struct bpf_object_open_opts *opts)
{
	struct master *obj;
	int err;

	obj = (struct master *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = master__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	master__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct master *
master__open(void)
{
	return master__open_opts(NULL);
}

static inline int
master__load(struct master *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct master *
master__open_and_load(void)
{
	struct master *obj;
	int err;

	obj = master__open();
	if (!obj)
		return NULL;
	err = master__load(obj);
	if (err) {
		master__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
master__attach(struct master *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
master__detach(struct master *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *master__elf_bytes(size_t *sz);

static inline int
master__create_skeleton(struct master *obj)
{
	struct bpf_object_skeleton *s;
	struct bpf_map_skeleton *map __attribute__((unused));
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "master";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = 24;
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt,
			sizeof(*s->maps) > 24 ? sizeof(*s->maps) : 24);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	map = (struct bpf_map_skeleton *)((char *)s->maps + 0 * s->map_skel_sz);
	map->name = "rb";
	map->map = &obj->maps.rb;

	s->data = master__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *master__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x18\x08\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x14\0\
\x01\0\x47\x50\x4c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\x11\x01\x25\
\x25\x13\x05\x03\x25\x72\x17\x10\x17\x1b\x25\x73\x17\0\0\x02\x34\0\x03\x25\x49\
\x13\x3f\x19\x3a\x0b\x3b\x0b\x02\x18\0\0\x03\x01\x01\x49\x13\0\0\x04\x21\0\x49\
\x13\x37\x0b\0\0\x05\x24\0\x03\x25\x3e\x0b\x0b\x0b\0\0\x06\x24\0\x03\x25\x0b\
\x0b\x3e\x0b\0\0\x07\x13\x01\x0b\x0b\x3a\x0b\x3b\x0b\0\0\x08\x0d\0\x03\x25\x49\
\x13\x3a\x0b\x3b\x0b\x38\x0b\0\0\x09\x0f\0\x49\x13\0\0\x0a\x21\0\x49\x13\x37\
\x06\0\0\0\x85\0\0\0\x05\0\x01\x08\0\0\0\0\x01\0\x1d\0\x01\x08\0\0\0\0\0\0\0\
\x02\x08\0\0\0\x02\x03\x29\0\0\0\x01\x08\x02\xa1\0\x03\x35\0\0\0\x04\x39\0\0\0\
\x04\0\x05\x04\x06\x01\x06\x05\x08\x07\x02\x06\x48\0\0\0\x02\x1d\x02\xa1\x01\
\x07\x10\x02\x1a\x08\x07\x5f\0\0\0\x02\x1b\0\x08\x09\x74\0\0\0\x02\x1c\x08\0\
\x09\x64\0\0\0\x03\x70\0\0\0\x04\x39\0\0\0\x1b\0\x05\x08\x05\x04\x09\x79\0\0\0\
\x03\x70\0\0\0\x0a\x39\0\0\0\0\0\x04\0\0\0\x2c\0\0\0\x05\0\0\0\0\0\0\0\x15\0\0\
\0\x50\0\0\0\x84\0\0\0\x8d\0\0\0\x92\0\0\0\xa6\0\0\0\xa9\0\0\0\xae\0\0\0\xb2\0\
\0\0\x63\x6c\x61\x6e\x67\x20\x76\x65\x72\x73\x69\x6f\x6e\x20\x32\x31\x2e\x31\
\x2e\x36\0\x2f\x68\x6f\x6d\x65\x2f\x65\x73\x6b\x65\x2f\x44\x6f\x63\x75\x6d\x65\
\x6e\x74\x73\x2f\x67\x69\x74\x2f\x4f\x64\x69\x6e\x53\x69\x67\x68\x74\x2f\x65\
\x62\x70\x66\x2f\x68\x6f\x6f\x6b\x73\x2f\x6d\x61\x73\x74\x65\x72\x2e\x62\x70\
\x66\x2e\x63\0\x2f\x68\x6f\x6d\x65\x2f\x65\x73\x6b\x65\x2f\x44\x6f\x63\x75\x6d\
\x65\x6e\x74\x73\x2f\x67\x69\x74\x2f\x4f\x64\x69\x6e\x53\x69\x67\x68\x74\x2f\
\x62\x75\x69\x6c\x64\x2f\x65\x62\x70\x66\x2f\x68\x6f\x6f\x6b\x73\0\x5f\x6c\x69\
\x63\x65\x6e\x73\x65\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\
\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x72\x62\0\x74\x79\x70\x65\0\x69\x6e\
\x74\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x14\0\0\0\x05\0\x08\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x04\x01\0\0\x04\
\x01\0\0\x49\0\0\0\0\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\
\x20\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x1b\0\0\0\x05\0\0\0\
\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x06\0\0\0\0\0\0\0\0\0\0\x03\0\
\0\0\0\x02\0\0\0\x04\0\0\0\0\0\x04\0\0\0\0\0\x02\0\0\x04\x10\0\0\0\x19\0\0\0\
\x01\0\0\0\0\0\0\0\x1e\0\0\0\x05\0\0\0\x40\0\0\0\x2a\0\0\0\0\0\0\x0e\x07\0\0\0\
\x01\0\0\0\x2d\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\
\x09\0\0\0\x04\0\0\0\x04\0\0\0\x32\0\0\0\0\0\0\x0e\x0a\0\0\0\x01\0\0\0\x3b\0\0\
\0\x01\0\0\x0f\0\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\x41\0\0\0\x01\0\0\x0f\0\0\0\
\0\x0b\0\0\0\0\0\0\0\x04\0\0\0\0\x69\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\
\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x74\x79\x70\x65\0\x6d\x61\x78\
\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x72\x62\0\x63\x68\x61\x72\0\x5f\x6c\x69\x63\
\x65\x6e\x73\x65\0\x2e\x6d\x61\x70\x73\0\x6c\x69\x63\x65\x6e\x73\x65\0\x6d\0\0\
\0\x05\0\x08\0\x65\0\0\0\x08\x01\x01\xfb\x0e\x0d\0\x01\x01\x01\x01\0\0\0\x01\0\
\0\x01\x01\x01\x1f\x02\0\0\0\0\x34\0\0\0\x03\x01\x1f\x02\x0f\x05\x1e\x03\x57\0\
\0\0\0\x4b\x92\x49\x9c\x93\xaf\x75\x7b\xec\xa8\x3a\x33\x22\x46\xe8\xa4\x92\0\0\
\0\x01\x4b\x92\x49\x9c\x93\xaf\x75\x7b\xec\xa8\x3a\x33\x22\x46\xe8\xa4\xaa\0\0\
\0\x01\x77\xb5\x16\x1e\x1e\x2d\xe0\x06\xf9\xa9\x84\x74\x06\xb3\x59\x1e\x2f\x68\
\x6f\x6d\x65\x2f\x65\x73\x6b\x65\x2f\x44\x6f\x63\x75\x6d\x65\x6e\x74\x73\x2f\
\x67\x69\x74\x2f\x4f\x64\x69\x6e\x53\x69\x67\x68\x74\x2f\x62\x75\x69\x6c\x64\
\x2f\x65\x62\x70\x66\x2f\x68\x6f\x6f\x6b\x73\0\x2f\x68\x6f\x6d\x65\x2f\x65\x73\
\x6b\x65\x2f\x44\x6f\x63\x75\x6d\x65\x6e\x74\x73\x2f\x67\x69\x74\x2f\x4f\x64\
\x69\x6e\x53\x69\x67\x68\x74\0\x2f\x68\x6f\x6d\x65\x2f\x65\x73\x6b\x65\x2f\x44\
\x6f\x63\x75\x6d\x65\x6e\x74\x73\x2f\x67\x69\x74\x2f\x4f\x64\x69\x6e\x53\x69\
\x67\x68\x74\x2f\x65\x62\x70\x66\x2f\x68\x6f\x6f\x6b\x73\x2f\x6d\x61\x73\x74\
\x65\x72\x2e\x62\x70\x66\x2e\x63\0\x65\x62\x70\x66\x2f\x68\x6f\x6f\x6b\x73\x2f\
\x6d\x61\x73\x74\x65\x72\x2e\x62\x70\x66\x2e\x63\0\x65\x62\x70\x66\x2f\x69\x6e\
\x63\x6c\x75\x64\x65\x2f\x65\x62\x70\x66\x5f\x74\x79\x70\x65\x73\x2e\x68\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x94\0\0\0\x04\0\xf1\xff\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x03\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x0a\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x0b\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x03\0\x0f\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x11\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x7b\0\0\0\x11\0\x03\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\
\0\0\xa1\0\0\0\x11\0\x04\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\
\x03\0\0\0\x02\0\0\0\x11\0\0\0\0\0\0\0\x03\0\0\0\x03\0\0\0\x15\0\0\0\0\0\0\0\
\x03\0\0\0\x06\0\0\0\x1a\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x08\0\0\0\0\0\0\0\
\x03\0\0\0\x04\0\0\0\x0c\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x10\0\0\0\0\0\0\0\
\x03\0\0\0\x04\0\0\0\x14\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x18\0\0\0\0\0\0\0\
\x03\0\0\0\x04\0\0\0\x1c\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x20\0\0\0\0\0\0\0\
\x03\0\0\0\x04\0\0\0\x24\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x28\0\0\0\0\0\0\0\
\x03\0\0\0\x04\0\0\0\x2c\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x08\0\0\0\0\0\0\0\
\x02\0\0\0\x08\0\0\0\x10\0\0\0\0\0\0\0\x02\0\0\0\x09\0\0\0\xfc\0\0\0\0\0\0\0\
\x04\0\0\0\x09\0\0\0\x14\x01\0\0\0\0\0\0\x04\0\0\0\x08\0\0\0\x22\0\0\0\0\0\0\0\
\x03\0\0\0\x07\0\0\0\x26\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\x32\0\0\0\0\0\0\0\
\x03\0\0\0\x07\0\0\0\x47\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\x5c\0\0\0\0\0\0\0\
\x03\0\0\0\x07\0\0\0\x08\x09\0\x2e\x64\x65\x62\x75\x67\x5f\x61\x62\x62\x72\x65\
\x76\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x73\
\x74\x72\x5f\x6f\x66\x66\x73\x65\x74\x73\0\x2e\x6d\x61\x70\x73\0\x2e\x64\x65\
\x62\x75\x67\x5f\x73\x74\x72\0\x2e\x64\x65\x62\x75\x67\x5f\x6c\x69\x6e\x65\x5f\
\x73\x74\x72\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x61\x64\x64\x72\0\
\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x69\x6e\x66\x6f\0\x2e\x6c\x6c\x76\
\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\
\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x6c\x69\x6e\x65\0\x6d\x61\x73\x74\x65\
\x72\x2e\x62\x70\x66\x2e\x63\0\x72\x62\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\
\x79\x6d\x74\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa4\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x5a\x07\0\0\0\0\0\0\xbd\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x0f\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x7c\
\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2c\0\0\0\x01\0\0\0\
\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x58\0\0\0\0\0\0\0\x75\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x61\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\xcd\0\0\0\0\0\0\0\x89\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x5d\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe8\x05\0\0\0\0\
\0\0\x40\0\0\0\0\0\0\0\x13\0\0\0\x06\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\
\x19\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x56\x01\0\0\0\0\0\0\x30\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x15\0\0\0\x09\0\
\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x28\x06\0\0\0\0\0\0\xa0\0\0\0\0\0\0\0\
\x13\0\0\0\x08\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x32\0\0\0\x01\0\0\0\
\x30\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x86\x01\0\0\0\0\0\0\xbe\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x51\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x44\x02\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4d\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\xc8\x06\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x13\0\0\0\x0b\0\0\0\x08\0\0\0\0\0\
\0\0\x10\0\0\0\0\0\0\0\xb8\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5c\
\x02\0\0\0\0\0\0\x65\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\xb4\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe8\x06\0\0\0\0\
\0\0\x20\0\0\0\0\0\0\0\x13\0\0\0\x0d\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\
\x88\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc1\x03\0\0\0\0\0\0\x71\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x84\0\0\0\x09\0\
\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\x07\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\
\x13\0\0\0\x0f\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x3d\0\0\0\x01\0\0\0\
\x30\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x32\x04\0\0\0\0\0\0\xc4\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x6d\0\0\0\x03\x4c\xff\x6f\0\0\0\
\x80\0\0\0\0\0\0\0\0\0\0\0\0\x58\x07\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\x13\0\0\0\0\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xac\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\xf8\x04\0\0\0\0\0\0\xf0\0\0\0\0\0\0\0\x01\0\0\0\x08\0\0\0\x08\0\
\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct master *master::open(const struct bpf_object_open_opts *opts) { return master__open_opts(opts); }
struct master *master::open_and_load() { return master__open_and_load(); }
int master::load(struct master *skel) { return master__load(skel); }
int master::attach(struct master *skel) { return master__attach(skel); }
void master::detach(struct master *skel) { master__detach(skel); }
void master::destroy(struct master *skel) { master__destroy(skel); }
const void *master::elf_bytes(size_t *sz) { return master__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
master__assert(struct master *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __MASTER_SKEL_H__ */
